---
- hosts: dolibarr
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # see https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user
    ansible_common_remote_group: "{{pac}}"
    ansible_remote_tmp: ~/.ansible/tmp

  tasks:
  - name: Create user, domain and database
    import_tasks: tasks/hs_basis.yml

  #################################
  ## create directories
  #################################
  - name: create directory bin
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/bin"
      state: directory

  #################################
  ## install data directory
  #################################
  - name: Check for HDD storage
    stat:
      path: /home/storage/{{pac}}/users/{{user}}
    register: hdd_storage
  - name: create data directory on storage
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/storage/{{pac}}/users/{{user}}/data"
      state: directory
      mode: 0744
    when: hdd_storage.stat.exists

  - name: create symbolic link for data to storage
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      src: "/home/storage/{{pac}}/users/{{user}}/data"
      dest: "/home/pacs/{{pac}}/users/{{user}}/data"
      state: link
    when: hdd_storage.stat.exists

  - name: create data directory on ssd
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/data"
      state: directory
      mode: 0744
    when: not hdd_storage.stat.exists

  ##################################
  ## install dolibarr
  ##################################
  - name: Check for git working tree
    become: yes
    become_user: "{{pac}}-{{user}}"
    stat:
      path: /home/pacs/{{pac}}/users/{{user}}/dolibarr
    register: workingtree
  - name: get dolibarr repo
    become: yes
    become_user: "{{pac}}-{{user}}"
    git:
      repo: https://github.com/dolibarr/dolibarr.git
      version: "{{dolibarr_branch}}"
      dest: /home/pacs/{{pac}}/users/{{user}}/dolibarr
    when: not workingtree.stat.exists

  ##################################
  ## configuration
  ##################################
  - name: copy config file
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/dolibarr/htdocs/conf/conf.php" src="templates/conf.php" mode=0600

  - name: upload sql script
    become: yes
    become_user: "{{pac}}-{{user}}"
    template:
      src: "templates/sql.sh"
      dest: "/home/pacs/{{pac}}/users/{{user}}/bin/sql.sh"
      mode: '0744'

  ######################
  ## initialise instance
  ######################
  - name: copy install config file
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/dolibarr/htdocs/install/install.forced.php" src="templates/install_forced.php" mode=0400

  - name: install the instance
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: |
      php step1.php /home/pacs/{{pac}}/users/{{user}}/dolibarr/htdocs/ || exit -1
      php step2.php set {{admin_language}} || exit -1
      php step5.php "" "" {{admin_language}} set {{admin_username}} "{{initial_admin_password}}" "{{initial_admin_password}}" || exit -1
      touch /home/pacs/{{pac}}/users/{{user}}/.dolibarr_initialised
    args:
        executable: /bin/bash
        chdir: "/home/pacs/{{pac}}/users/{{user}}/dolibarr/htdocs/install"
        creates: /home/pacs/{{pac}}/users/{{user}}/.dolibarr_initialised

  ########################
  ## setup the apache site
  ########################
  - name: drop htdocs-ssl
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
       path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
       state: absent

  - name: create symbolic link for htdocs-ssl
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      src: "/home/pacs/{{pac}}/users/{{user}}/dolibarr/htdocs"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
      state: link
